# Generated by Django 4.1.4 on 2023-03-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
