# Generated by Django 4.1.4 on 2023-03-14 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_termin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='first_name',
            field=models.CharField(db_column='imie', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='last_name',
            field=models.CharField(db_column='nazwisko', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(db_column='nazwa_uzytkownika', default='user', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='password',
            field=models.CharField(db_column='haslo', max_length=50),
        ),
    ]
