# Generated by Django 4.1.4 on 2023-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_uzytkownik_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='first_name',
            field=models.CharField(db_column='imie', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='last_name',
            field=models.CharField(db_column='nazwisko', max_length=50, null=True),
        ),
    ]
