# Generated by Django 4.1.4 on 2023-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_uzytkownik_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='password',
            field=models.CharField(db_column='haslo', max_length=150),
        ),
    ]
