# Generated by Django 4.1.4 on 2023-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_uzytkownik_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='pesel',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
