# Generated by Django 4.1.4 on 2023-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_uzytkownik_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='nr_telefonu',
            field=models.IntegerField(null=True),
        ),
    ]
