# Generated by Django 4.1.7 on 2023-03-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_uzytkownik_nr_telefonu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='pesel',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
